### ISSUE TITLE
Error Handling.

### ISSUE THREAD

**Issue by ikyman** [Aasiya3/ElephantBook_FieldGuide#41]
Was looking through Database Wrapper, found 
{ err ->
                println("BRSAKAI_ERR")
                println(err) // TODO Error handling
}
So I guess the issue is error handling.

**Comment by bsakai2000** [comment]
Code referenced in the issue is https://github.com/Aasiya3/ElephantBook_FieldGuide/blob/b63c8dc4c2f54ce5793c7c1046e9c13f14d89a1f/app/src/main/java/com/example/elephantbook_fieldguide/DatabaseWrapper.kt#L61-L64

Tried to clean this up in the `demo` branch using a Toast notification, but this issue is probably blocked by the UI team until we have a good way to provide feedback to the user
https://github.com/Aasiya3/ElephantBook_FieldGuide/blob/a523b08558e9c4df0b053efa546dd98ff9e4c56f/app/src/main/java/com/example/elephantbook_fieldguide/DatabaseWrapper.kt#L63-L66
